"""Actualización de modelos con datos faltantes

Revision ID: 803a5ac151a8
Revises: 
Create Date: 2025-02-26 09:30:22.955177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803a5ac151a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datos_mdms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_masas_patron', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vr_masas_patron', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tolerancia_vr', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tolerancia_cero', sa.Float(), nullable=True))

    with op.batch_alter_table('vqm_mdm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cant1_verif1_valor_masico', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cant1_verif1_valor_bascula', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cant1_verif2_valor_masico', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cant1_verif2_valor_bascula', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cant2_verif1_valor_masico', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cant2_verif1_valor_bascula', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cant2_verif2_valor_masico', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cant2_verif2_valor_bascula', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vqm_mdm', schema=None) as batch_op:
        batch_op.drop_column('cant2_verif2_valor_bascula')
        batch_op.drop_column('cant2_verif2_valor_masico')
        batch_op.drop_column('cant2_verif1_valor_bascula')
        batch_op.drop_column('cant2_verif1_valor_masico')
        batch_op.drop_column('cant1_verif2_valor_bascula')
        batch_op.drop_column('cant1_verif2_valor_masico')
        batch_op.drop_column('cant1_verif1_valor_bascula')
        batch_op.drop_column('cant1_verif1_valor_masico')

    with op.batch_alter_table('datos_mdms', schema=None) as batch_op:
        batch_op.drop_column('tolerancia_cero')
        batch_op.drop_column('tolerancia_vr')
        batch_op.drop_column('vr_masas_patron')
        batch_op.drop_column('id_masas_patron')

    # ### end Alembic commands ###
